version: "3"

services:
  LunarFM:
    container_name: LunarFM
    image: nodejs
    build: .
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD

    networks:
      - app-network

networks:
  app-network:
    external: true
