"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const data_access_1 = __importDefault(require("./data-access"));
const express = require("express");
const path = require("path");
const cookieParser = require("cookie-parser");
const logger = require("morgan");
const cors = require("cors");
const indexRouter = require("./routes/index");
const usersRouter = require("./routes/users");
const podcasts_1 = __importDefault(require("./routes/podcasts"));
const radioStations_1 = __importDefault(require("./routes/radioStations"));
const events_1 = __importDefault(require("./routes/events"));
const episodeRouter = require("./routes/episodes");
const albums_1 = __importDefault(require("./routes/albums"));
const tracks_1 = __importDefault(require("./routes/tracks"));
const artists_1 = __importDefault(require("./routes/artists"));
const genreRouter = require("./routes/genres");
const hostRouter = require("./routes/hosts");
(0, data_access_1.default)();
const app = express();
app.use(cors());
app.use(logger("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use("/api", indexRouter);
app.use("/api/users", usersRouter);
app.use("/api/podcasts", podcasts_1.default);
app.use("/api/radioStations", radioStations_1.default);
app.use("/api/events", events_1.default);
app.use("/api/episodes", episodeRouter);
app.use("/api/albums", albums_1.default);
app.use("/api/tracks", tracks_1.default);
app.use("/api/artist", artists_1.default);
app.use("/api/genres", genreRouter);
app.use("/api/hosts", hostRouter);
//set static folder
app.use(express.static(path.join(__dirname, "/build")));
app.use(express.static(path.join(__dirname, "/public")));
app.get("*", (_, res) => {
    res.sendFile(path.join(__dirname, "build"));
    res.sendFile(path.join(__dirname, "build", "index.html"));
});
module.exports = app;
